version: '3'
services:
  api:
    image: node:latest
    working_dir: /api
    volumes:
      - type: bind
        source: ./api
        target: /code

  db:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=cohabit
    volumes:
      - "./api/dbConfig:/docker-entrypoint-initdb.d/:ro"
